title: Zyad Alshuja
logo: https://github.com/zyadalshujaa1/Zyad.github.io/assets/91574172/80c83be8-dde6-4556-a4a5-bdbf44ed458c

description: Mechatronics, Robotics, and Automation Engineering
show_downloads: true
theme: jekyll-theme-minimal
